#pragma once

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define DEBOUNCE 8
#define USE_INTERNAL_PULLUP
// #define ENCODER_MAP_KEY_DELAY 10

// #define NO_USB_WAKE_FROM_SUSPEND
// #define RGB_MATRIX_SLEEP

#define ENCODER_DIRECTION_FLIP
#define ENCODER_RESOLUTIONS { 2, 4 }

#define LED_NUM_LOCK_PIN GP25

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP12
#define I2C1_SCL_PIN GP13
#define I2C1_CLOCK_SPEED 400000

#define OLED_IC OLED_IC_SSD1306
#define OLED_DISPLAY_128X64
#define OLED_BRIGHTNESS 255
#define OLED_TIMEOUT 300000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 2
#define OLED_FONT_END 127

//#define SERIAL_USART_FULL_DUPLEX
// #define SERIAL_USART_TX_PIN GP16
// #define SERIAL_USART_RX_PIN GP17
// #define SERIAL_USART_DRIVER SIOD0
// #define SELECT_SOFT_SERIAL_SPEED 2 //115200
#define UART_TX_PIN GP16
#define UART_RX_PIN GP17

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_LIMIT_VAL 120
