
#pragma once

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define DEBOUNCE 8
#define USE_INTERNAL_PULLUP
// #define ENCODER_MAP_KEY_DELAY 10

// #define NO_USB_WAKE_FROM_SUSPEND
// #define RGB_MATRIX_SLEEP


#define ENCODERS_PAD_A { GP14, GP26 }
#define ENCODERS_PAD_B { GP11, GP11 }
#define ENCODER_DIRECTION_FLIP
#define ENCODER_RESOLUTIONS { 2, 4 }

#define LED_NUM_LOCK_PIN GP25

#define OLED_IC OLED_IC_SSD1306
#define I2C_DRIVER I2CD0
#define OLED_DISPLAY_128X64
#define OLED_BRIGHTNESS 255
// #define OLED_DISPLAY_ADDRESS 0x3D
//   #define OLED_DISPLAY_ADDRESS 0x7B
#define I2C1_SDA_PIN GP12
#define I2C1_SCL_PIN GP13
#define I2C1_CLOCK_SPEED 400000
#define OLED_TIMEOUT 300000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 2
#define OLED_FONT_END 127


#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_HUE_STEP 2
#define RGBLIGHT_SAT_STEP 2
#define RGBLIGHT_VAL_STEP 2