
RGBLIGHT_ENABLE = yes
RGB_MATRIX_SUPPORTED = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
NKRO_ENABLE = no

NO_SUSPEND_POWER_DOWN = yes

# BOARD = GENERIC_RP_RP2040

OLED_ENABLE = yes
OLED_TRANSPORT = i2c
OPT_DEFS += -DHAL_USE_I2C=TRUE
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes