
RGBLIGHT_ENABLE = yes
RGBLIGHT_ANIMATIONS = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk


NO_SUSPEND_POWER_DOWN = yes

OLED_ENABLE = yes
OLED_TRANSPORT = i2c
OPT_DEFS += -DHAL_USE_I2C=TRUE
OLED_DRIVER_ENABLE = yes
